services:
  - type: web
    name: leettracker-backend
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false # Set this in Render dashboard (Atlas URI)
      - key: SPRING_DATA_REDIS_HOST
        fromService:
          type: redis
          name: leettracker-redis
          property: host
      - key: SPRING_DATA_REDIS_PORT
        fromService:
          type: redis
          name: leettracker-redis
          property: port
      - key: SPRING_DATA_REDIS_REPOSITORIES_ENABLED
        value: "false"
      - key: JWT_SECRET
        generateValue: true

  - type: redis
    name: leettracker-redis
    plan: free
    region: singapore
    ipAllowList: [] # Only allow internal connections
